-- ─────────────────────────────────────────────────────────────────────────
-- BR Kitchen Hub — Phase 1 foundation schema
-- Tenancy & identity, RBAC, settings, audit, and passwordless OTP auth.
--
-- Conventions:
--   * IDs are TEXT UUIDs generated by the application (crypto.randomUUID()).
--   * All money (added in later phases) is stored as INTEGER cents. No money
--     lives in this migration yet.
--   * Timestamps are TEXT ISO-8601 UTC (strftime). The kitchen timezone
--     (Australia/Brisbane) is applied only at presentation time.
--   * Foreign keys are declared; enable enforcement per-connection with
--     `PRAGMA foreign_keys = ON` (the D1 client does this).
--   * `deleted_at` marks soft deletes; it is only added where an entity must
--     be retained for history, not on append-only tables.
-- ─────────────────────────────────────────────────────────────────────────

-- ── Operators ────────────────────────────────────────────────────────────
-- Top-level tenant: the business that owns one or more kitchens. A single
-- operator exists today; the column threads through every scoped table so
-- multi-operator expansion never requires a destructive migration.
CREATE TABLE operators (
  id           TEXT PRIMARY KEY,
  name         TEXT NOT NULL,
  legal_name   TEXT,
  abn          TEXT,
  timezone     TEXT NOT NULL DEFAULT 'Australia/Brisbane',
  currency     TEXT NOT NULL DEFAULT 'AUD',
  status       TEXT NOT NULL DEFAULT 'active'
                 CHECK (status IN ('active', 'suspended', 'archived')),
  created_at   TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ', 'now')),
  updated_at   TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ', 'now')),
  deleted_at   TEXT
);

-- ── Kitchens ─────────────────────────────────────────────────────────────
CREATE TABLE kitchens (
  id           TEXT PRIMARY KEY,
  operator_id  TEXT NOT NULL REFERENCES operators(id),
  name         TEXT NOT NULL,
  slug         TEXT NOT NULL,
  description  TEXT,
  address_line TEXT,
  suburb       TEXT,
  state        TEXT NOT NULL DEFAULT 'QLD',
  postcode     TEXT,
  timezone     TEXT NOT NULL DEFAULT 'Australia/Brisbane',
  status       TEXT NOT NULL DEFAULT 'active'
                 CHECK (status IN ('active', 'inactive', 'archived')),
  created_at   TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ', 'now')),
  updated_at   TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ', 'now')),
  deleted_at   TEXT
);
CREATE UNIQUE INDEX idx_kitchens_slug ON kitchens(slug);
CREATE INDEX idx_kitchens_operator ON kitchens(operator_id);

-- ── Kitchen spaces ───────────────────────────────────────────────────────
-- A bookable area within a kitchen (e.g. "Main Production Bench", "Pastry
-- Station"). Bookings and check-ins attach to a space, so multi-space
-- scheduling works from day one.
CREATE TABLE kitchen_spaces (
  id          TEXT PRIMARY KEY,
  kitchen_id  TEXT NOT NULL REFERENCES kitchens(id),
  name        TEXT NOT NULL,
  kind        TEXT NOT NULL DEFAULT 'shared'
                CHECK (kind IN ('shared', 'private', 'prep', 'other')),
  capacity    INTEGER NOT NULL DEFAULT 1 CHECK (capacity >= 0),
  status      TEXT NOT NULL DEFAULT 'active'
                CHECK (status IN ('active', 'inactive', 'maintenance')),
  created_at  TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ', 'now')),
  updated_at  TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ', 'now'))
);
CREATE INDEX idx_kitchen_spaces_kitchen ON kitchen_spaces(kitchen_id);

-- ── Users (auth identity only) ───────────────────────────────────────────
-- Minimal authentication record. Personal data lives in `profiles`; business
-- data lives in `organisations`. Keeping them apart satisfies the brief's
-- separation requirement.
CREATE TABLE users (
  id                TEXT PRIMARY KEY,
  email             TEXT NOT NULL,
  email_verified_at TEXT,
  status            TEXT NOT NULL DEFAULT 'active'
                      CHECK (status IN ('active', 'invited', 'suspended')),
  last_login_at     TEXT,
  created_at        TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ', 'now')),
  updated_at        TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ', 'now')),
  deleted_at        TEXT
);
-- Case-insensitive unique email.
CREATE UNIQUE INDEX idx_users_email ON users(lower(email));

-- ── Profiles (personal data) ─────────────────────────────────────────────
CREATE TABLE profiles (
  user_id                   TEXT PRIMARY KEY REFERENCES users(id),
  full_name                 TEXT,
  phone                     TEXT,
  preferred_contact_method  TEXT
                              CHECK (preferred_contact_method IN
                                ('email', 'phone', 'sms', NULL)),
  avatar_url                TEXT,
  timezone                  TEXT NOT NULL DEFAULT 'Australia/Brisbane',
  created_at                TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ', 'now')),
  updated_at                TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ', 'now'))
);

-- ── Organisations (customer businesses) ──────────────────────────────────
CREATE TABLE organisations (
  id             TEXT PRIMARY KEY,
  operator_id    TEXT NOT NULL REFERENCES operators(id),
  name           TEXT NOT NULL,
  legal_name     TEXT,
  abn            TEXT,
  website        TEXT,
  instagram      TEXT,
  business_type  TEXT,
  stage          TEXT,
  status         TEXT NOT NULL DEFAULT 'prospect'
                   CHECK (status IN
                     ('prospect', 'onboarding', 'active', 'suspended', 'inactive')),
  created_at     TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ', 'now')),
  updated_at     TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ', 'now')),
  deleted_at     TEXT
);
CREATE INDEX idx_organisations_operator ON organisations(operator_id);

-- ── Organisation members (user ↔ organisation) ───────────────────────────
CREATE TABLE organisation_members (
  id               TEXT PRIMARY KEY,
  organisation_id  TEXT NOT NULL REFERENCES organisations(id),
  user_id          TEXT NOT NULL REFERENCES users(id),
  role_in_org      TEXT NOT NULL DEFAULT 'member'
                     CHECK (role_in_org IN
                       ('owner', 'manager', 'chef', 'staff', 'member')),
  status           TEXT NOT NULL DEFAULT 'invited'
                     CHECK (status IN ('invited', 'active', 'suspended', 'removed')),
  invited_at       TEXT,
  joined_at        TEXT,
  created_at       TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ', 'now')),
  updated_at       TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ', 'now'))
);
CREATE UNIQUE INDEX idx_org_members_unique ON organisation_members(organisation_id, user_id);
CREATE INDEX idx_org_members_user ON organisation_members(user_id);

-- ── Role assignments (RBAC) ──────────────────────────────────────────────
-- Authorisation is enforced server-side by resolving a user's assignments
-- into capabilities. `scope_type`/`scope_id` bind a role to a tenant slice:
--   global       -> super admin, scope_id NULL
--   operator     -> operator-wide admin/staff
--   kitchen      -> kitchen-scoped admin/staff
--   organisation -> customer owner/member for one business
CREATE TABLE role_assignments (
  id          TEXT PRIMARY KEY,
  user_id     TEXT NOT NULL REFERENCES users(id),
  role        TEXT NOT NULL
                CHECK (role IN
                  ('super_admin', 'kitchen_admin', 'staff',
                   'customer_owner', 'customer_member')),
  scope_type  TEXT NOT NULL
                CHECK (scope_type IN ('global', 'operator', 'kitchen', 'organisation')),
  scope_id    TEXT,
  created_at  TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ', 'now')),
  created_by  TEXT REFERENCES users(id)
);
CREATE UNIQUE INDEX idx_role_assignments_unique
  ON role_assignments(user_id, role, scope_type, IFNULL(scope_id, ''));
CREATE INDEX idx_role_assignments_user ON role_assignments(user_id);
CREATE INDEX idx_role_assignments_scope ON role_assignments(scope_type, scope_id);

-- ── System settings (generic, scoped key/value) ──────────────────────────
-- Backs every "administrable text / config" requirement: business details,
-- GST defaults, invoice prefix, booking/tour rules, etc. Scope lets the same
-- table hold global defaults and per-kitchen overrides, so a dedicated
-- kitchen_settings table is not needed yet.
CREATE TABLE system_settings (
  id          TEXT PRIMARY KEY,
  scope_type  TEXT NOT NULL DEFAULT 'global'
                CHECK (scope_type IN ('global', 'operator', 'kitchen')),
  scope_id    TEXT,
  key         TEXT NOT NULL,
  value       TEXT,                 -- JSON-encoded value
  updated_at  TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ', 'now')),
  updated_by  TEXT REFERENCES users(id)
);
CREATE UNIQUE INDEX idx_system_settings_unique
  ON system_settings(scope_type, IFNULL(scope_id, ''), key);

-- ── Audit log (append-only) ──────────────────────────────────────────────
CREATE TABLE audit_logs (
  id            TEXT PRIMARY KEY,
  actor_user_id TEXT REFERENCES users(id),
  actor_label   TEXT,                 -- denormalised for readability/system actors
  action        TEXT NOT NULL,        -- e.g. 'role.granted', 'settings.updated'
  entity_type   TEXT NOT NULL,
  entity_id     TEXT,
  before_json   TEXT,
  after_json    TEXT,
  ip            TEXT,
  metadata_json TEXT,
  created_at    TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ', 'now'))
);
CREATE INDEX idx_audit_logs_entity ON audit_logs(entity_type, entity_id);
CREATE INDEX idx_audit_logs_actor ON audit_logs(actor_user_id);
CREATE INDEX idx_audit_logs_created ON audit_logs(created_at);

-- ── Passwordless OTP ─────────────────────────────────────────────────────
-- Codes are stored hashed (never plaintext). Send throttling and verify
-- attempts are tracked to resist brute force and spam.
CREATE TABLE auth_otps (
  id           TEXT PRIMARY KEY,
  email        TEXT NOT NULL,
  code_hash    TEXT NOT NULL,
  purpose      TEXT NOT NULL DEFAULT 'login'
                 CHECK (purpose IN ('login', 'invitation')),
  expires_at   TEXT NOT NULL,
  consumed_at  TEXT,
  attempts     INTEGER NOT NULL DEFAULT 0,
  created_at   TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ', 'now'))
);
CREATE INDEX idx_auth_otps_email ON auth_otps(lower(email), created_at);
